language: python
dist: bionic

services:
  - docker

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - python3 -m pytest tests
  - docker build -t openfoodfacts/robotoff .
  - echo "$DOCKER_PASSWORD" | docker login --password-stdin -u "$DOCKER_USERNAME"
  - docker push openfoodfacts/robotoff
