language: python

services:
  - docker

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - python3 -m pytest tests
  - docker build -t openfoodfacts/robotoff .
  - docker push openfoodfacts/robotoff
