language: python
dist: bionic

services:
  - docker

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - python3 -m pytest tests
  - docker build -t openfoodfacts/robotoff:dev .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push openfoodfacts/robotoff
