language: python
dist: bionic

services:
  - docker

python:
  - "3.6"
  - "3.7"

jobs:
  include:
    - stage: test
      install:
        - pip install -r requirements.txt
      script: python3 -m pytest tests
    - stage: deploy
      if: tag =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?
      script:
        - docker build -t openfoodfacts/robotoff:latest .
        - docker tag openfoodfacts/robotoff:latest openfoodfacts/robotoff:${TRAVIS_TAG:1}
        - echo "$DOCKER_PASSWORD" | docker login --password-stdin -u "$DOCKER_USERNAME"
        - docker push openfoodfacts/robotoff
