version: '3'

services:
  api:
    image: openfoodfacts/robotoff
    ports:
      - "5500:5500"
    volumes:
    - api-dataset:/opt/rbt/datasets
    environment:
      DB_HOST: "postgres"
      ELASTICSEARCH_HOSTS: "elasticsearch"

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"

  elasticsearch:
    image: raphael0202/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  api-dataset:
    external: true
