version: '3'

services:
  api:
    image: openfoodfacts/robotoff
    network_mode: "host"
    volumes:
    - api-dataset:/opt/robotoff/datasets
    - ./tf_models:/opt/robotoff/tf_models:Z
    environment:
      DB_HOST: "localhost"
      ELASTICSEARCH_HOSTS: "elasticsearch"
      IPC_HOST: "localhost"

  workers:
    image: openfoodfacts/robotoff
    volumes:
      - api-dataset:/opt/robotoff/datasets
      - ./tf_models:/opt/robotoff/tf_models:Z
    network_mode: "host"
    environment:
      DB_HOST: "localhost"
      ELASTICSEARCH_HOSTS: "localhost"
    entrypoint: "python3 robotoff.py run workers"

  scheduler:
    image: openfoodfacts/robotoff
    volumes:
      - api-dataset:/opt/robotoff/datasets
      - ./tf_models:/opt/robotoff/tf_models:Z
    environment:
      DB_HOST: "postgres"
      ELASTICSEARCH_HOSTS: "elasticsearch"
    entrypoint: "python3 robotoff.py run scheduler"

  postgres:
    image: postgres:11
    ports:
      - "127.0.0.1:5432:5432"

  elasticsearch:
    image: raphael0202/elasticsearch
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"

  tf_serving:
    image: tensorflow/serving:1.13.0
    ports:
      - "8501:8501"
      - "8500:8500"
    volumes:
      - ./tf_models:/models:Z
    entrypoint: "tensorflow_model_server --port=8500 --rest_api_port=8501 --model_config_file=/models/models.config"

volumes:
  api-dataset:
