version: '3'

services:
  api:
    image: openfoodfacts/robotoff
    network_mode: "host"
    volumes:
    - api-dataset:/opt/robotoff/datasets
    environment:
      DB_HOST: "localhost"
      ELASTICSEARCH_HOSTS: "elasticsearch"
      IPC_HOST: "localhost"

  workers:
    build:
      context: .
    volumes:
      - api-dataset:/opt/robotoff/datasets
    network_mode: "host"
    environment:
      DB_HOST: "localhost"
      ELASTICSEARCH_HOSTS: "localhost"
    entrypoint: "python3 robotoff.py run workers"

  scheduler:
    build:
      context: .
    volumes:
      - api-dataset:/opt/robotoff/datasets
    environment:
      DB_HOST: "postgres"
      ELASTICSEARCH_HOSTS: "elasticsearch"
    entrypoint: "python3 robotoff.py run scheduler"

  postgres:
    image: postgres:11
    ports:
      - "127.0.0.1:5432:5432"

  elasticsearch:
    image: raphael0202/elasticsearch
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"

volumes:
  api-dataset:
    external: true
