[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "robotoff"
version = "1.0.13"
description = "Real-time and batch prediction service for Openfoodfacts"
authors = ["Openfoodfacts Team"]
license = "License :: OSI Approved :: GNU Affero General Public License v3"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
peewee = "^3.14.0"
psycopg2-binary = "^2.8.6"
gunicorn = "^20.0.4"
falcon = "^2.0.0"
falcon-cors = "^1.1.7"
falcon-multipart = "^0.2.0"
elasticsearch = "^7.10.1"
click = "^7.1.2"
sentry-sdk = {version = "^0.19.5", extras = ["falcon"]}
pymongo = "^3.11.2"
spacy = "^2.3.5"
dacite = "^1.6.0"
flashtext = "^2.7"
langid = "^1.1.6"
influxdb = "^5.3.1"
jsonschema = "^3.2.0"
orjson = "^3.4.6"
Pillow = "^8.1.0"
numpy = "^1.19.5"
protobuf = "^3.14.0"
Pint = "0.9"
APScheduler = "^3.6.3"
more-itertools = "^8.6.0"
scikit-learn = "^0.24.0"
sklearn-hierarchical-classification = "^1.3.2"
matplotlib = "^3.3.3"
tensorflow = "^2.4.1"
scipy = "^1.6.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.4"
black = "^20.8b1"
mypy = "^0.790"
pytest = "^6.2.1"
pytest-mock = "^3.5.1"
pre-commit = "^2.9.3"
toml-sort = "^0.18.0"
isort = "^5.7.0"
